[build]
  base = "frontend"        # go into frontend folder
  command = "npm run build"
  publish = "dist"         # frontend/dist will be deployed

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
